title: About Flora Tasse
description: When science and art meets, magic follows ...
google_analytics: UA-62050220-1
show_downloads: false
theme: jekyll-theme-slate

github:
  is_project_page: false
  hide_view_on_github: true
  
gems:
  - jekyll-mentions
